"""
PDF Generator utility using ReportLab for comprehensive reporting.
Generates professional PDF reports with SAPNA CARTING branding.
"""

from io import BytesIO
from datetime import datetime
from decimal import Decimal
from typing import List, Dict, Any, Optional, Tuple

from django.db.models import QuerySet, Sum, Count, Avg
from django.template.loader import render_to_string

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, KeepTogether
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY

# Custom colors matching SAPNA CARTING brand
SAPNA_BLACK = colors.Color(0, 0, 0, 1)  # slate-900 equivalent
SAPNA_AMBER = colors.Color(1, 0.69, 0.3, 1)  # amber-500 equivalent
LIGHT_GRAY = colors.Color(0.96, 0.96, 0.96, 1)  # gray-50
MEDIUM_GRAY = colors.Color(0.75, 0.75, 0.75, 1)  # gray-400
DARK_GRAY = colors.Color(0.37, 0.37, 0.37, 1)  # gray-600


class BasePDFReport:
    """Base class for PDF reports with common functionality."""
    
    def __init__(self, filename: str = "report.pdf"):
        self.filename = filename
        self.buffer = BytesIO()
        self.doc = SimpleDocTemplate(
            self.buffer,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=3*cm,
            bottomMargin=2*cm
        )
        self.styles = getSampleStyleSheet()
        self._setup_styles()
        self.story = []
        
    def _setup_styles(self):
        """Setup custom styles matching brand."""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            textColor=SAPNA_BLACK,
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Header style
        self.styles.add(ParagraphStyle(
            name='CustomHeader',
            parent=self.styles['Heading1'],
            fontSize=16,
            textColor=SAPNA_BLACK,
            spaceAfter=12,
            alignment=TA_LEFT,
            fontName='Helvetica-Bold'
        ))
        
        # Subheader style
        self.styles.add(ParagraphStyle(
            name='CustomSubheader',
            parent=self.styles['Heading2'],
            fontSize=12,
            textColor=SAPNA_BLACK,
            spaceAfter=8,
            alignment=TA_LEFT,
            fontName='Helvetica-Bold'
        ))
        
        # Normal text style
        self.styles.add(ParagraphStyle(
            name='CustomNormal',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=SAPNA_BLACK,
            spaceAfter=6,
            alignment=TA_LEFT,
            fontName='Helvetica'
        ))
        
        # Company header style
        self.styles.add(ParagraphStyle(
            name='CompanyHeader',
            parent=self.styles['Normal'],
            fontSize=20,
            textColor=SAPNA_AMBER,
            spaceAfter=5,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Footer style
        self.styles.add(ParagraphStyle(
            name='FooterStyle',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=MEDIUM_GRAY,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))

    def add_company_header(self):
        """Add SAPNA CARTING company header."""
        self.story.append(Spacer(1, 0.5*inch))
        self.story.append(Paragraph("SAPNA CARTING", self.styles['CompanyHeader']))
        self.story.append(Paragraph("Fleet Management System", self.styles['CustomNormal']))
        self.story.append(Spacer(1, 0.3*inch))

    def add_title(self, title: str):
        """Add report title."""
        self.story.append(Paragraph(title, self.styles['CustomTitle']))
        self.story.append(Spacer(1, 0.2*inch))

    def add_metadata(self, date_from: str = None, date_to: str = None, generated_by: str = None):
        """Add report metadata."""
        metadata = []
        if date_from or date_to:
            if date_from and date_to:
                metadata.append(f"Period: {date_from} to {date_to}")
            elif date_from:
                metadata.append(f"Period: {date_from} to Present")
            elif date_to:
                metadata.append(f"Period: Until {date_to}")
        
        if generated_by:
            metadata.append(f"Generated by: {generated_by}")
        
        metadata.append(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        if metadata:
            for item in metadata:
                self.story.append(Paragraph(item, self.styles['CustomNormal']))
        self.story.append(Spacer(1, 0.3*inch))

    def add_table(self, data: List[List], headers: List[str] = None, column_widths: List[float] = None) -> Table:
        """Create and add a styled table."""
        if headers:
            table_data = [headers] + data
        else:
            table_data = data
        
        if column_widths:
            table = Table(table_data, colWidths=[w * inch for w in column_widths])
        else:
            # Calculate equal column widths
            cols = len(table_data[0]) if table_data else 1
            col_width = (A4[0] - 4*cm) / cols
            table = Table(table_data, colWidths=[col_width] * cols)
        
        # Style the table
        style = [
            # Header styling
            ('BACKGROUND', (0, 0), (-1, 0), SAPNA_AMBER),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            
            # Data rows
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
            
            # Border styling
            ('GRID', (0, 0), (-1, -1), 1, MEDIUM_GRAY),
            ('LINEBELOW', (0, 0), (-1, 0), 2, SAPNA_BLACK),
            
            # Alternating row colors
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
        ]
        
        table.setStyle(TableStyle(style))
        self.story.append(table)
        self.story.append(Spacer(1, 0.2*inch))
        return table

    def add_summary(self, title: str, summary_data: Dict[str, Any]):
        """Add summary section with key metrics."""
        self.story.append(Paragraph(title, self.styles['CustomHeader']))
        
        # Create summary table
        summary_table_data = []
        for key, value in summary_data.items():
            summary_table_data.append([key, str(value)])
        
        if summary_table_data:
            self.add_table(summary_table_data, ['Metric', 'Value'])
        
        self.story.append(Spacer(1, 0.2*inch))

    def add_page_break(self):
        """Add page break."""
        self.story.append(PageBreak())

    def add_footer(self, page_num: int):
        """Add footer with page number."""
        footer_text = f"Page {page_num} | SAPNA CARTING Fleet Management | Generated on {datetime.now().strftime('%Y-%m-%d')}"
        footer = Paragraph(footer_text, self.styles['FooterStyle'])
        return footer

    def format_currency(self, amount: Decimal) -> str:
        """Format currency values."""
        return f"₹{amount:,.2f}"

    def format_percentage(self, value: Decimal) -> str:
        """Format percentage values."""
        return f"{value:.1f}%"

    def build(self):
        """Build the PDF document."""
        # Build the story
        self.doc.build(self.story, onFirstPage=self._add_footer, onLaterPages=self._add_footer)
        
        # Get the PDF content
        pdf_content = self.buffer.getvalue()
        self.buffer.close()
        
        return pdf_content

    def _add_footer(self, canvas, doc):
        """Add footer to each page."""
        canvas.saveState()
        footer_text = f"SAPNA CARTING Fleet Management | Page {doc.page}"
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(MEDIUM_GRAY)
        canvas.drawCentredText(A4[0] / 2, 0.5 * inch, footer_text)
        canvas.restoreState()


class FuelConsumptionPDF(BasePDFReport):
    """PDF generator for fuel consumption reports."""
    
    def generate(self, fuel_logs: QuerySet, date_from: str = None, date_to: str = None, 
                 user: str = None) -> bytes:
        """Generate fuel consumption PDF report."""
        self.add_company_header()
        self.add_title("Fuel Consumption Report")
        self.add_metadata(date_from, date_to, user)
        
        # Summary data
        total_liters = fuel_logs.aggregate(total=Sum('fuel_liters'))['total'] or Decimal('0')
        total_cost = fuel_logs.aggregate(total=Sum('fuel_cost'))['total'] or Decimal('0')
        total_distance = sum(
            log.odometer - log.previous_odometer 
            for log in fuel_logs 
            if log.previous_odometer > 0
        )
        
        avg_efficiency = (total_distance / total_liters) if total_liters > 0 else Decimal('0')
        
        summary_data = {
            'Total Fuel Purchased': f"{total_liters:.2f} liters",
            'Total Fuel Cost': self.format_currency(total_cost),
            'Total Distance': f"{total_distance:,} km",
            'Average Efficiency': f"{avg_efficiency:.2f} km/l",
        }
        
        self.add_summary("Summary", summary_data)
        
        # Detailed data table
        if fuel_logs:
            table_headers = ['Date', 'Truck', 'Driver', 'Liters', 'Cost', 'Odometer', 'Efficiency']
            table_data = []
            
            for log in fuel_logs:
                efficiency = (log.odometer - log.previous_odometer) / log.fuel_liters if log.fuel_liters > 0 else 0
                table_data.append([
                    log.date.strftime('%Y-%m-%d'),
                    log.truck.plate_number,
                    log.driver.name,
                    f"{log.fuel_liters:.2f}",
                    self.format_currency(log.fuel_cost),
                    f"{log.odometer:,}",
                    f"{efficiency:.2f} km/l" if efficiency > 0 else "N/A"
                ])
            
            self.add_table(table_data, table_headers)
        
        return self.build()


class TireCostPDF(BasePDFReport):
    """PDF generator for tire cost reports."""
    
    def generate(self, tires: QuerySet, user: str = None) -> bytes:
        """Generate tire cost PDF report."""
        self.add_company_header()
        self.add_title("Tire Cost Analysis Report")
        self.add_metadata(None, None, user)
        
        # Summary data
        total_cost = sum(tire.calculate_total_cost() for tire in tires)
        total_tires = tires.count()
        avg_cost_per_km = sum(tire.calculate_cost_per_km() for tire in tires) / total_tires if total_tires > 0 else 0
        
        summary_data = {
            'Total Tire Investment': self.format_currency(Decimal(str(total_cost))),
            'Total Tires': str(total_tires),
            'Average Cost per KM': f"₹{avg_cost_per_km:.4f}",
        }
        
        self.add_summary("Summary", summary_data)
        
        # Detailed data table
        if tires:
            table_headers = ['Serial Number', 'Brand', 'Truck', 'Status', 'Purchase Cost', 'Total Cost', 'Current Mileage', 'Cost per KM']
            table_data = []
            
            for tire in tires:
                table_data.append([
                    tire.serial_number,
                    tire.brand,
                    tire.truck.plate_number if tire.truck else 'Not Mounted',
                    tire.get_status_display(),
                    self.format_currency(tire.purchase_cost),
                    self.format_currency(Decimal(str(tire.calculate_total_cost()))),
                    f"{tire.calculate_current_mileage():,} km",
                    f"₹{tire.calculate_cost_per_km():.4f}" if tire.calculate_cost_per_km() > 0 else "N/A"
                ])
            
            self.add_table(table_data, table_headers)
        
        return self.build()


class OperationsPDF(BasePDFReport):
    """PDF generator for operations reports."""
    
    def generate(self, coal_logs: QuerySet, mining_logs: QuerySet, date_from: str = None, 
                 date_to: str = None, user: str = None) -> bytes:
        """Generate operations summary PDF report."""
        self.add_company_header()
        self.add_title("Operations Summary Report")
        self.add_metadata(date_from, date_to, user)
        
        # Summary data
        total_coal_trips = coal_logs.count()
        total_coal_tonnage = sum(log.net_weight for log in coal_logs) or Decimal('0')
        total_mining_trips = mining_logs.count()
        total_mining_tonnage = sum(log.net for log in mining_logs) or Decimal('0')
        
        summary_data = {
            'Coal Trips': str(total_coal_trips),
            'Coal Tonnage': f"{total_coal_tonnage:.2f} MT",
            'Mining Trips': str(total_mining_trips),
            'Mining Tonnage': f"{total_mining_tonnage:.2f} MT",
        }
        
        self.add_summary("Summary", summary_data)
        
        # Coal logs table
        if coal_logs:
            self.add_title("Coal Logs")
            table_headers = ['Date', 'Truck', 'Pass No', 'Net Weight', 'Origin', 'Destination']
            table_data = []
            
            for log in coal_logs:
                table_data.append([
                    log.date.strftime('%Y-%m-%d'),
                    log.truck.plate_number,
                    log.pass_no,
                    f"{log.net_weight:.2f} MT",
                    log.origin_site,
                    log.destination_site
                ])
            
            self.add_table(table_data, table_headers)
        
        # Mining logs table
        if mining_logs:
            self.add_title("Mining Logs")
            table_headers = ['Date', 'Truck', 'Chalan No', 'Customer', 'Net Weight', 'Material']
            table_data = []
            
            for log in mining_logs:
                table_data.append([
                    log.date.strftime('%Y-%m-%d'),
                    log.truck.plate_number,
                    log.chalan_no,
                    log.customer_name,
                    f"{log.net:.2f} MT",
                    log.material
                ])
            
            self.add_table(table_data, table_headers)
        
        return self.build()


class FleetStatusPDF(BasePDFReport):
    """PDF generator for fleet status reports."""
    
    def generate(self, trucks: QuerySet, user: str = None) -> bytes:
        """Generate fleet status PDF report."""
        self.add_company_header()
        self.add_title("Fleet Status Report")
        self.add_metadata(None, None, user)
        
        # Summary data
        active_trucks = trucks.filter(status='ACTIVE').count()
        maintenance_trucks = trucks.filter(status='MAINTENANCE').count()
        inactive_trucks = trucks.filter(status='INACTIVE').count()
        
        summary_data = {
            'Active Trucks': str(active_trucks),
            'Maintenance Trucks': str(maintenance_trucks),
            'Inactive Trucks': str(inactive_trucks),
            'Total Fleet': str(trucks.count()),
        }
        
        self.add_summary("Fleet Summary", summary_data)
        
        # Detailed data table
        if trucks:
            table_headers = ['Plate Number', 'Type', 'Status', 'Current Odometer', 'Fitness', 'Insurance', 'Tax', 'Permit']
            table_data = []
            
            for truck in trucks:
                fitness_color = truck.get_expiry_color_code(truck.fitness_expiry)
                insurance_color = truck.get_expiry_color_code(truck.insurance_expiry)
                tax_color = truck.get_expiry_color_code(truck.tax_expiry)
                permit_color = truck.get_expiry_color_code(truck.permit_expiry)
                
                table_data.append([
                    truck.plate_number,
                    truck.get_fleet_type_display(),
                    truck.get_status_display(),
                    f"{truck.current_odometer:,} km",
                    f"{truck.fitness_expiry.strftime('%Y-%m-%d') if truck.fitness_expiry else 'N/A'}",
                    f"{truck.insurance_expiry.strftime('%Y-%m-%d') if truck.insurance_expiry else 'N/A'}",
                    f"{truck.tax_expiry.strftime('%Y-%m-%d') if truck.tax_expiry else 'N/A'}",
                    f"{truck.permit_expiry.strftime('%Y-%m-%d') if truck.permit_expiry else 'N/A'}",
                ])
            
            self.add_table(table_data, table_headers)
        
        return self.build()


class DriverPerformancePDF(BasePDFReport):
    """PDF generator for driver performance reports."""
    
    def generate(self, drivers: QuerySet, fuel_logs: QuerySet, date_from: str = None, 
                 date_to: str = None, user: str = None) -> bytes:
        """Generate driver performance PDF report."""
        self.add_company_header()
        self.add_title("Driver Performance Report")
        self.add_metadata(date_from, date_to, user)
        
        # Calculate driver performance metrics
        driver_metrics = []
        for driver in drivers:
            driver_fuel_logs = fuel_logs.filter(driver=driver)
            if driver_fuel_logs.exists():
                total_liters = sum(log.fuel_liters for log in driver_fuel_logs)
                total_cost = sum(log.fuel_cost for log in driver_fuel_logs)
                trips = driver_fuel_logs.count()
                total_distance = sum(
                    log.odometer - log.previous_odometer 
                    for log in driver_fuel_logs 
                    if log.previous_odometer > 0
                )
                avg_efficiency = (total_distance / total_liters) if total_liters > 0 else 0
                
                driver_metrics.append({
                    'driver': driver,
                    'trips': trips,
                    'total_liters': total_liters,
                    'total_cost': total_cost,
                    'total_distance': total_distance,
                    'avg_efficiency': avg_efficiency
                })
        
        # Summary data
        total_trips = sum(m['trips'] for m in driver_metrics)
        total_drivers = len(driver_metrics)
        
        summary_data = {
            'Total Drivers': str(total_drivers),
            'Total Trips': str(total_trips),
            'Average Trips per Driver': f"{total_trips / total_drivers:.1f}" if total_drivers > 0 else "0",
        }
        
        self.add_summary("Summary", summary_data)
        
        # Detailed driver table
        if driver_metrics:
            table_headers = ['Driver Name', 'License No', 'Trips', 'Total Liters', 'Total Cost', 'Total Distance', 'Avg Efficiency']
            table_data = []
            
            for metric in sorted(driver_metrics, key=lambda x: x['avg_efficiency'], reverse=True):
                table_data.append([
                    metric['driver'].name,
                    metric['driver'].license_number,
                    str(metric['trips']),
                    f"{metric['total_liters']:.2f}",
                    self.format_currency(metric['total_cost']),
                    f"{metric['total_distance']:,} km",
                    f"{metric['avg_efficiency']:.2f} km/l"
                ])
            
            self.add_table(table_data, table_headers)
        
        return self.build()


class CostPerKmPDF(BasePDFReport):
    """PDF generator for cost per km analysis reports."""
    
    def generate(self, truck_metrics: List[Dict], user: str = None) -> bytes:
        """Generate cost per km analysis PDF report."""
        self.add_company_header()
        self.add_title("Cost Per KM Analysis Report")
        self.add_metadata(None, None, user)
        
        # Summary data
        avg_cost_per_km = sum(m['cost_per_km'] for m in truck_metrics) / len(truck_metrics) if truck_metrics else 0
        best_truck = min(truck_metrics, key=lambda x: x['cost_per_km']) if truck_metrics else None
        worst_truck = max(truck_metrics, key=lambda x: x['cost_per_km']) if truck_metrics else None
        
        summary_data = {
            'Average Cost per KM': f"₹{avg_cost_per_km:.4f}",
            'Best Performer': best_truck['truck'].plate_number if best_truck else 'N/A',
            'Worst Performer': worst_truck['truck'].plate_number if worst_truck else 'N/A',
        }
        
        self.add_summary("Summary", summary_data)
        
        # Detailed data table
        if truck_metrics:
            table_headers = ['Truck', 'Total KM', 'Fuel Cost', 'Tire Cost', 'Total Cost', 'Cost per KM']
            table_data = []
            
            for metric in truck_metrics:
                table_data.append([
                    metric['truck'].plate_number,
                    f"{metric['total_km']:,} km",
                    self.format_currency(metric['fuel_cost']),
                    self.format_currency(metric['tire_cost']),
                    self.format_currency(metric['total_cost']),
                    f"₹{metric['cost_per_km']:.4f}"
                ])
            
            self.add_table(table_data, table_headers)
        
        return self.build()


class FleetEfficiencyPDF(BasePDFReport):
    """PDF generator for fleet efficiency comparison reports."""
    
    def generate(self, efficiency_data: List[Dict], user: str = None) -> bytes:
        """Generate fleet efficiency comparison PDF report."""
        self.add_company_header()
        self.add_title("Fleet Efficiency Comparison Report")
        self.add_metadata(None, None, user)
        
        # Summary data
        avg_efficiency = sum(d['efficiency'] for d in efficiency_data) / len(efficiency_data) if efficiency_data else 0
        best_efficiency = max(efficiency_data, key=lambda x: x['efficiency']) if efficiency_data else None
        
        summary_data = {
            'Average Efficiency': f"{avg_efficiency:.2f} km/l",
            'Best Performer': f"{best_efficiency['truck'].plate_number} ({best_efficiency['efficiency']:.2f} km/l)" if best_efficiency else 'N/A',
            'Fleet Size': str(len(efficiency_data)),
        }
        
        self.add_summary("Summary", summary_data)
        
        # Detailed data table
        if efficiency_data:
            table_headers = ['Truck', 'Efficiency (km/l)', 'Distance', 'Fuel Used', 'Performance vs Average']
            table_data = []
            
            for data in efficiency_data:
                vs_avg = data['efficiency'] - avg_efficiency
                vs_avg_str = f"+{vs_avg:.2f}" if vs_avg > 0 else f"{vs_avg:.2f}"
                
                table_data.append([
                    data['truck'].plate_number,
                    f"{data['efficiency']:.2f}",
                    f"{data['total_distance']:,} km",
                    f"{data['total_fuel']:.2f} liters",
                    vs_avg_str
                ])
            
            self.add_table(table_data, table_headers)
        
        return self.build()


class PredictiveMaintenancePDF(BasePDFReport):
    """PDF generator for predictive maintenance reports."""
    
    def generate(self, maintenance_alerts: List[Dict], user: str = None) -> bytes:
        """Generate predictive maintenance PDF report."""
        self.add_company_header()
        self.add_title("Predictive Maintenance Report")
        self.add_metadata(None, None, user)
        
        # Summary data
        critical_alerts = len([a for a in maintenance_alerts if a['priority'] == 'CRITICAL'])
        warning_alerts = len([a for a in maintenance_alerts if a['priority'] == 'WARNING'])
        info_alerts = len([a for a in maintenance_alerts if a['priority'] == 'INFO'])
        
        summary_data = {
            'Critical Alerts': str(critical_alerts),
            'Warning Alerts': str(warning_alerts),
            'Info Alerts': str(info_alerts),
            'Total Alerts': str(len(maintenance_alerts)),
        }
        
        self.add_summary("Alert Summary", summary_data)
        
        # Detailed alerts table
        if maintenance_alerts:
            table_headers = ['Truck', 'Priority', 'Alert Type', 'Description', 'Recommendation']
            table_data = []
            
            # Sort by priority (Critical first, then Warning, then Info)
            priority_order = {'CRITICAL': 1, 'WARNING': 2, 'INFO': 3}
            sorted_alerts = sorted(maintenance_alerts, key=lambda x: priority_order.get(x['priority'], 4))
            
            for alert in sorted_alerts:
                table_data.append([
                    alert['truck'].plate_number,
                    alert['priority'],
                    alert['alert_type'],
                    alert['description'],
                    alert['recommendation']
                ])
            
            self.add_table(table_data, table_headers)
        
        return self.build()